### ISSUE TITLE
 RuntimeWarning: Unexpected end-group tag: Not all data was converted

### ISSUE THREAD

**Issue by abhijeet0007** [matlink/gplaycli#150]
when use the command  gplaycli -v -pd com.whatsapp it shown this type of error 

root@localhost:~# gplaycli -v -pd com.whatsapp
[INFO] GPlayCli version 3.12 [Python3.5.2]
[INFO] Configuration file is /root/.config/gplaycli/gplaycli.conf
[INFO] Using cached token.
[INFO] Using auto retrieved token to connect to API
/usr/local/lib/python3.5/dist-packages/gpapi/googleplay.py:275: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  message = googleplay_pb2.ResponseWrapper.FromString(response.content)

1 :  when i am removing the token by this command  rm -rf .cache/gplaycli/token , it will be run fine but after the couple of time the gplaycli show the same type of error

2 : when i config the gplaycli.conf and put the token value false it will this kind of error

[INFO] GPlayCli version 3.12 [Python3.5.2]
[INFO] Configuration file is gplaycli.conf
[INFO] Using credentials to connect to API
[INFO] Using plaintext password
[INFO] Token has expired or is invalid. Retrieving a new one...
[ERROR] cache file does not exists or is corrupted
[INFO] Retrieving token ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 217, in connect_to_googleplay_api
    gsfId=gsfId)
  File "/usr/local/lib/python3.5/dist-packages/gpapi/googleplay.py", line 184, in login
    raise LoginError("server says: " + params["error"])
gpapi.googleplay.LoginError: 'server says: BadAuthentication'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.12', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 537, in main
    success, error = cli.connect_to_googleplay_api()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 220, in connect_to_googleplay_api
    self.refresh_token()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 225, in refresh_token
    self.retrieve_token(force_new=True)
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 170, in retrieve_token
    r = requests.get(self.token_url)
AttributeError: 'GPlaycli' object has no attribute 'token_url

previously the token= False is working good for me with my own credentials 

any of the solutions can't work
@matlink please help me out 

![capture](https://user-images.githubusercontent.com/14326082/34155317-e55e006e-e4de-11e7-9b0e-4a070d1866ec.JPG)

I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [ Ubuntu 16.04 ] Operating System (ie Ubuntu 16.04)
- [ Python 3.5.2 ] Python version when running `gplaycli` (should be 2.7 for now)
- [ 3.12 ] GPlayCli version via `gplaycli -v`
- [pip3 install gplaycli ] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [default ] The authentication method: (own) credentials or (own) token.

**Comment by matlink** [comment]
Please try with gplaycli version 3.14

**Comment by abhijeet0007** [comment]
thank you @matlink but still token=False isn't working for me

**Comment by matlink** [comment]
Version 3.15 should resolve that issue. It was a regression introduced when fixing the RuntimeWarning.

**Comment by Elasti-Shabbir** [comment]
I am getting the same error in version 3.15

**Comment by rehmatworks** [comment]
@Elasti-Shabbir probably you didn't update it properly. I confirm that v3.15 addresses this issue completely.

**Comment by matlink** [comment]
@Elasti-Shabbir please post a trace of execution with verbose argument (-v).
Moreover, try to install gplaycli in a new virtualenv to make sure you're up-to-date with every dependency.

**Comment by Phoenix09** [comment]
@Elasti-Shabbir is it really 3.15?
because pypi is still on 3.14 so you'll need to install from git.
as I already thought I updated, saw this error in my cron emails today, saw this issue, updated, still not working, checked version, still 3.14, checked pypi and it's outdated, updated to 3.15 from git, working.

**Comment by matlink** [comment]
I've published it to pypi, it's my fault, I thought I had done it.

**Comment by Elasti-Shabbir** [comment]
Installed it in new virtual env and everything is working fine as of now.

**Comment by acim** [comment]
It seems this bug reappeared in 3.29.

```
/home/xxx/.local/lib/python3.8/site-packages/gpapi/googleplay.py:645: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  response = googleplay_pb2.ResponseWrapper.FromString(response.content)
```

**Comment by shrishabh** [comment]
Anyone else facing the same issue? I am using version 3.29 and facing the same warning. 

```
/home/xxx/.local/lib/python3.5/site-packages/gpapi/googleplay.py:645: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  response = googleplay_pb2.ResponseWrapper.FromString(response.content)
```

**Comment by aatv** [comment]
@shrishabh yes, I am getting this with 3.29
